### ISSUE TITLE
Parsing bool values raises exception

### ISSUE THREAD

**Issue by bergmannjg** [Zaid-Ajaj/Fable.SimpleJson.Python#3]
The below code

```f#
type Type4 = { t: string; b: bool }

let json = """{"t": "abc", "b": true}"""

Json.parseNativeAs<Type4> json |> ignore
```
raises an exception
```
Exception: Cannot convert true to Bool
```

The code works after reordering the lines

https://github.com/Zaid-Ajaj/Fable.SimpleJson.Python/blob/18be08fca527c3d2f5fa8168889ccef2aeaebfa5/src/SimpleJson.fs#L48-L49

I think the type bool needs to be checked first, because [bool is a subclass of int](https://stackoverflow.com/questions/37888620/comparing-boolean-and-int-using-isinstance)

* dotnet fable-py version: 4.0.0-alpha-032
* Fable.SimpleJson.Python version: 1.1.0

**Comment by Zaid-Ajaj** [comment]
Hi @bergmannjg thanks a lot for filing the issue and for investigating it 🙏 it's fixed it as of v1.2.0 :rocket: added support for System.Uri while I was at it
